services:
  rabbitmq:
    image: rabbitmq:4
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
      - rabbit-data:/var/lib/rabbitmq:rw
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 12

  server:
    build:
      dockerfile: ../Dockerfile
      context: server/
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    ports:
      - "5000:5000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data


volumes:
  rabbit-data:
  redis-data:
